### ISSUE TITLE
Multiply Missing?

### ISSUE THREAD

**Issue by nekropants** [penandlim/JL-s-Unity-Blend-Modes#3]
Hi this library is absolutely fantastic thank you!
The only thing is that it appears to be missing the multiply shader?

-Rich

**Comment by penandlim** [comment]
Hey Im not sure if this repo still works but multiply was possible through unity's default blend mode.

https://github.com/penandlim/JL-s-Unity-Blend-Modes/issues/1#issuecomment-439309950

Blend DstColor Zero is what you want probably.
